# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd4d5d8d5205c2e03f41da5eaa5f9398e139e192b7be281d545764c2f1ed8925e15d107bbc84b1bb91a93989203b8afc6888a26f1126f4af963600f64291389c

test:
  secret_key_base: 8e49f6dd184d57a0d7676cebfc782bdfa77e91b96334f047fae698e4c69178fa55f5ef4bc85b2f85737735cb927a1310b02727f5a48c62e3950a54932e74fb3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
